### ISSUE TITLE
Is the concept 'InteractionMethod' needed? 

### ISSUE THREAD

**Issue by gothub** [codemeta/codemeta#110]
Datacite has a mapping to this concept in the crosswalk table, and this term is related to the
DataCite term  'ResourceTypeGeneral' from the [DataCite API](http://schema.datacite.org/meta/kernel-3/doc/DataCite-MetadataKernel_v3.1.pdf), the controlled
list for this is "Audiovisual, Collection, Dataset, Event, Image, InteractiveResource, Model, PhysicalObject, Service, Software, Sound, Text20, Workflow, Other".

Since CodeMeta descriptions are always type "Software", do we need this concept?

**Comment by 7048730** [comment]
Could CodeMeta descriptions refer to something DataCite would classify as 'InteractiveResource'? In the document you refer to, this element is defined as 

> A resource requiring interaction from the user to be understood, executed, or experienced.

Since not all kinds of software require user interaction or at least the same sort or level of user interaction, this information could be a valuable addition to CodeMeta.

**Comment by nuest** [comment]
Would it be possible to extend the controlled list (above which could be used for the _output_ generated by  software.. do I need speakers to use it?) with items for differents inputs, such as `command-line-interface` or `graphical user interface`. That is certainly useful to know about a software.

Or can these aspects be defined somewhere else (apologies, I'm new to Codemeta!) ?

**Comment by mbjones** [comment]
DataCite is the only spec that includes this field, so its not common -- its used in DataCite to differentiate different types of records, such as Dataset from Software.  As all CodeMeta documents should be describing Software, there isn't any reason for this specific field -- it would always be set to the constant 'Software'.  

There's value in the comments about methods for interacting with the software, but I think that really represents a different concept, more related to how someone uses the software than the fact that it *is* software, which is what the DataCite vocabulary listed above classifies.  Some software provides a CLI, some a GUI, some a service, and some can provide any combination of these when deployed.  Describing those is a comlex thing, and if we want to do that, we probably should develop out a use case for how it would be used. So, given that I'm not sure how such a field would be used in our current use cases, for now I'm going to support @gothub's suggestion that we remove the field. If such a use case gets developed, we could definitely consider adding one or more fields to support that case.  But for now I'd like to move on this so we can get a tagged release out.  @cboettig, let us know if you disagree, otherwise we'll go ahead along these lines.

**Comment by cboettig** [comment]
I agree. Full steam ahead

**Comment by gothub** [comment]
I confirmed that the term `interactionmethod` is not being used by CodeMeta, and has been marked as 'unneeded' in the [concepts document](https://github.com/codemeta/codemeta/blob/master/codemeta-concepts.md) and the crosswalk csv.
