### ISSUE TITLE
Migrate unit tests to R jsonld

### ISSUE THREAD

**Issue by gothub** [codemeta/codemeta#124]
The new library R [jsonld](https://github.com/ropensci/jsonld) is now available. Should we migrate the CodeMeta unit tests (currently in ./minitest) to the R equivalent?

The current tests use the [ruby jsonld](https://github.com/ruby-rdf/json-ld) library.
Points to consider for continuing to use the ruby library:
- the unit tests are working except for a recent problem with a new release
- the tests use ruby gems that may not have equivalents in R:
   - sparql'
   - 'rdf/nquads
   - json-schema
   - easy_diff (for comparing json documents)

Points in favor of R
- we like R
- what else?

**Comment by cboettig** [comment]
Basically thinking about maintaining the tests going forward, my ruby is pretty weak myself and this might be a good playground for me trying these things in R.  We get rdf from the jsonld package and json-schema from jsonvalidate package.  Doesn't R redlands do sparql?  (Otherwise rrdf does).  Not sure about easy_diff for json diffs, maybe @jeroenooms knows about that?

**Comment by gothub** [comment]
@cboettig @jeroenooms the test that uses easy_diff could be refactored to use some other mechanism for the test. I don't think this is a blocker.
