### ISSUE TITLE
Homepage term

### ISSUE THREAD

**Issue by moranegg** [codemeta/codemeta#148]
I'm trying to figure out how to address the "homepage" term existing in many manifest files but in some cases in the crosswalk table are mapped to relatedLink or url (schema.org: "URL of the item") or codeRepository.

What should be the proper place for homepage?

**Comment by cboettig** [comment]
Right, ultimately this depends a bit on the context of the software in question (as reflected by the crosswalk; though most of our crosswalk was the result of small teams in a two day workshop, so arguably could be improved). 

If the homepage is a `codeRepository` (e.g. a version control remote endpoint), I'd suggest using the more explicit `codeRepository`, otherwise I'd go with `url`.   I'd think of url as a more "canonical link", while `relatedLink` is more of a bucket for links that just don't seem to fit anywhere else.

**Comment by moranegg** [comment]
thanks for your answer.

i think I should do a run through the crosswalk table to see if this logic is kept.

**Comment by cboettig** [comment]
Closing as resolved, but feel free to ropen if `url` doesn't fit the bill
