### ISSUE TITLE
Create a codemeta.jsonld file for the v2 CodeMeta release 

### ISSUE THREAD

**Issue by gothub** [codemeta/codemeta#151]
This CodeMeta instance document should as fully as possible describe the v2.0 CodeMeta
release, and will serve as a useful CodeMeta example.

**Comment by cboettig** [comment]
@gothub Can you give me a rough timeline for getting around to this, just for my own planning purposes?

Sorry, I know you have a lot on your plate and we've probably already consumed your time.  Thanks for the help!

**Comment by gothub** [comment]
@cboettig I'll start work on this today, shouldn't take long, eh?

(I'm tantalizing close to releasing a new version
of `dataone` R package, so have had my blinders on for the last couple of days.)

**Comment by gothub** [comment]
A first pass at a CodeMeta 2.0 example file has been added in commit 55d1374dd7b99f1997095c5f0132fdbc0a2bd7d8

The name "example/codemeta-2.0.jsonld" may be confused with the schema file, suggestions
for an alternate filename are welcome.

Using the DOI in the context, this file doesn't translate in the JSON playground, the following error is
produced:

```
{
  "stack": "Error\n    at JsonLdError (https://cdnjs.cloudflare.com/ajax/libs/jsonld/0.4.2/jsonld.js:2358:19)\n    at done (https://cdnjs.cloudflare.com/ajax/libs/jsonld/0.4.2/jsonld.js:6741:19)\n    at <anonymous>",
  "name": "jsonld.InvalidUrl",
  "message": "Dereferencing a URL did not result in a valid JSON-LD object. Possible causes are an inaccessible URL perhaps due to a same-origin policy (ensure the server uses CORS if you are using client-side JavaScript), too many redirects, a non-JSON response, or more than one HTTP Link Header was provided for a remote context.",
  "details": {
    "code": "loading remote context failed",
    "url": "https://doi.org/doi:10.5063/schema/codemeta-2.0",
    "cause": {
      "stack": "Error\n    at JsonLdError (https://cdnjs.cloudflare.com/ajax/libs/jsonld/0.4.2/jsonld.js:2358:19)\n    at Object.error (https://cdnjs.cloudflare.com/ajax/libs/jsonld/0.4.2/jsonld.js:1718:18)\n    at j (https://cdn.jsdelivr.net/g/async@1.5.0,jquery@1.11.0,es6-promise@1.0.0,bootstrap@2.3.2,codemirror@3.22.0(codemirror.min.js+addon/lint/lint.js+addon/edit/matchbrackets.js+addon/edit/closebrackets.js+addon/display/placeholder.js+addon/hint/show-hint.js+mode/ntriples/ntriples.js+mode/javascript/javascript.js):1265:27136)\n    at Object.fireWith [as rejectWith] (https://cdn.jsdelivr.net/g/async@1.5.0,jquery@1.11.0,es6-promise@1.0.0,bootstrap@2.3.2,codemirror@3.22.0(codemirror.min.js+addon/lint/lint.js+addon/edit/matchbrackets.js+addon/edit/closebrackets.js+addon/display/placeholder.js+addon/hint/show-hint.js+mode/ntriples/ntriples.js+mode/javascript/javascript.js):1265:27949)\n    at x (https://cdn.jsdelivr.net/g/async@1.5.0,jquery@1.11.0,es6-promise@1.0.0,bootstrap@2.3.2,codemirror@3.22.0(codemirror.min.js+addon/lint/lint.js+addon/edit/matchbrackets.js+addon/edit/closebrackets.js+addon/display/placeholder.js+addon/hint/show-hint.js+mode/ntriples/ntriples.js+mode/javascript/javascript.js):1267:22269)\n    at XMLHttpRequest.b (https://cdn.jsdelivr.net/g/async@1.5.0,jquery@1.11.0,es6-promise@1.0.0,bootstrap@2.3.2,codemirror@3.22.0(codemirror.min.js+addon/lint/lint.js+addon/edit/matchbrackets.js+addon/edit/closebrackets.js+addon/display/placeholder.js+addon/hint/show-hint.js+mode/ntriples/ntriples.js+mode/javascript/javascript.js):1267:26298)",
      "name": "jsonld.LoadDocumentError",
      "message": "URL could not be dereferenced, an error occurred.",
      "details": {
        "code": "loading document failed",
        "url": "https://doi.org/doi:10.5063/schema/codemeta-2.0",
        "cause": ""
      }
    }
  }
}
```

I'm hoping that this is a CORS issue, will log an issue with the git repo for the playground tomorrow.
This should work with the recent changes to DataCite DOI resolution. I haven't tried any
other method to test the DOI resolution for a context file.

Using the github 2.0 tagged name for the schema file does work.

**Comment by cboettig** [comment]
Looks good to me!  

@mbjones Just so I get this right this time, you'll reserve a DOI for us for the `2.0.1` release and we'll want to edit this file to use that DOI and not the one shown above *before* we tag the git release, right?

Also, I just wanted clarification on a somewhat trivial issue: but I'm curious about the truly recommended way to list DOIs as URIs; e.g. you include the identifier namespace `doi:` in the doi URL: 

-  `https://doi.org/doi:10...` vs just 
-  `https://doi.org/10...` 

I realize both work (as does `http://`, and as does the I think largely historical `http://dx.doi.org`, but I note @mfenner's examples in the official DataCite stuff just go for the vanilla `https` address and never include the second `doi:`, as do the examples I see most publishers using.  So why add the `doi:`?  @mfenner care to weigh in on that as well?

**Comment by moranegg** [comment]
@gothub about the filename:  as I see it the codemeta-2.0.jsonld is the metadata representation of the CodeMeta project  and as such it is a special example of how repositories could keep a metadata file at the root directory.

In my research for intrinsic metadata kept inside the source code, this kind of file is better under a defined name, because it can be easily discovered. 

From my understanding with the CodeMeta vocabulary one should use CODE, code.json, codemeta.json at the root directory. This could be a formal recommendation in specs. 

For other examples about existing or fictional projects in the examples folder the options bellow seems appropriate :
- <project_name>_CODE
- <project_name>_code.json
- <project_name>_codemeta.json

**Comment by cboettig** [comment]
Oh right, re filename, we've been calling the metadata file `codemeta.json` most everywhere else, so that would be my vote (though I like code.json, matches paper.json of arfon & co).   I think the ideal thing would have been for us to have the jsonld context file in a `context` subdirectory or some such, I guess we could still move that.... (Yeah people may be used to it in the current locale and moving it would break code that is linking against the master branch directly, though after all we'd rather people link against the doi)

In any event, I think just stating what's what in the readme should suffice.

**Comment by mbjones** [comment]
I'd vote for the instance files to be named codemeta.json or code.json, and
reserve the name codemeta.jsonld for the context file.

**Comment by cboettig** [comment]
Thanks @mbjones !  In that case, @gothub , can you change the filename to just `codemeta.json` and mention this is the metadata file while the `.jsonld` one is the context file in the `README.md`?  

I think `codemeta.json` is the most common so far and a bit less ambiguous than `code.json`.

**Comment by gothub** [comment]
@cboettig So should this be in the top level directory in the repo, and not in the example
directory?

**Comment by cboettig** [comment]
I think so, yes.  That's consistent with how zenodo seems to be treating these, and where many systems place their own package metadata files (e.g. R, node, ruby).  

On the repo organization side, might be good to clear out anything no longer needed in this repo.  I think `docs` is all migrated to the website, except for some notes you had about dataone indexing which I wasn't sure what to do with yet.  I think the `data` files are also obsolete?  Good to keep `examples` and `tests` though.  

I feel `CONTRIBUTING.md` is redundant with the `codemeta.json` file you've created, and seems a bit confusing to be using both.  Do you think we can remove it?  

Also, do you think `webapp` can be forked out into a separate repo to keep this repo focused on the context file  / crosswalk? (also since it's deprecated by breaking changes to the context anyway...)

**Comment by gothub** [comment]
@cboettig `examples/codemeta-2.0.jsonld` has been renamed to `codemeta.json`. The directories `docs`, `data`, `webapp` have been removed. I'll find a home for `docs` and `webapp` somewhere else. The contents of `data` are no longer needed.

**Comment by cboettig** [comment]
Excellent, thanks.  I think we can close this.

@mbjones lets just hang off on the 2.1 release until we decide on #155.

**Comment by mfenner** [comment]
@cboettig please use https://doi.org/10.5555/1234, there is no reason to include `doi:` within the HTTP URI. See https://datacite.readme.io/docs/datacite-doi-display-guidelines and https://www.crossref.org/display-guidelines/ for details.

**Comment by cboettig** [comment]
Thanks @mfenner!  @gothub, can we switch to the example to the format Martin recommends?

**Comment by gothub** [comment]
[codemeta.json](https://github.com/codemeta/codemeta/commit/8222e294097cc795ec999eb8b3062224e969ee82#diff-825c48cfd9d909baadb0f1e3fdee98f1) now adheres to the DataCite recommended DOI URL format.

**Comment by cboettig** [comment]
Thanks!
