### ISSUE TITLE
.ABOUT files exported in libraries.io

### ISSUE THREAD

**Issue by moranegg** [codemeta/codemeta#152]
I was wondering if we should crosswalk the terms in the .ABOUT files available on libraries.io with the CodeMeta terms?

I was also wondering with what tool the .ABOUT is created, but this is a question to post on @librariesio

**Comment by cboettig** [comment]
Cool, keep me posted.

**Comment by andrew** [comment]
@moranegg we added `.ABOUT` file support to Libraries.io for @maxbrito, I've been meaning to add the equivalent `/codemeta.json` endpoint to every project and repository url which would remove the need for a crosswalk

**Comment by cboettig** [comment]
@andrew Thanks, that would be awesome

**Comment by andrew** [comment]
@cboettig added an issue to get done this month: https://github.com/librariesio/libraries.io/issues/1555

**Comment by maxbrito** [comment]
> I was also wondering with what tool the .ABOUT is created, but this is a question to post on @librariesio

There is an open source tool supported by the Google Of Code program: http://www.aboutcode.org/
and an online generator at http://triplecheck.tech/components/

In reality I see most people just quickly grabbing an ABOUT file from libraries.io and then using a plain text editor to specify which files or folders are applicable on their case, rather than using specific tools. These files are later read by tools that automatically generate inventories.

A crosswalk should be possible with the ABOUT format, the official specification is found at https://github.com/dejacode/ABOUTspec and I can contribute one if you wish.

The most relevant aspect of ABOUT is that they apply to specific files and/or folders inside the project, which is needed when different 3rd party s/w get mixed in the same folders and you need to describe exactly which files belong to which component. Maybe a field for specifying files/folders could be included on CodeMeta? 

Not related to this topic, but I enjoyed seeing the way CodeMeta specifies the link to the README. Would be great if we could have a link to the LICENSE file when that file is available inside a project. Cases like the MIT and BSD require the original text file to be included on the zip distribution of other projects, so this would certainly be a good help for tools and humans to easily find the original LICENSE for each third party.

**Comment by cboettig** [comment]
Thanks for the background on .ABOUT format.  Nice project.  Is that .html spec file hosted somewhere?

> Would be great if we could have a link to the LICENSE file when that file is available inside a project. Cases like the MIT and BSD require the original text file to be included on the zip distribution of other projects, so this would certainly be a good help for tools and humans to easily find the original LICENSE for each third party.

In the case of CodeMeta, the license field is inherited from <http://schema.org/license> which expects a type of `CreativeWork` or `URL`.   The URL could be to the original file, though we encourage the use of SPDX abbreviations and the corresponding SPDX URL for standardization.  Maybe that was already obvious to you.  I do see this is more subtle in the ABOUT context where you reflect what files are actually in a .zip software package rather than merely metadata about the package.

**Comment by maxbrito** [comment]
>  Is that .html spec file hosted somewhere?

This seems to be from the previous version but changes are minimal: http://www.dejacode.org/about_spec_v0.8.0.html

> In the case of CodeMeta, the license field is inherited from http://schema.org/license which expects a type of CreativeWork or URL.

Thanks, that should solve the case.

> The URL could be to the original file, though we encourage the use of SPDX abbreviations and the corresponding SPDX URL for standardization. Maybe that was already obvious to you. I do see this is more subtle in the ABOUT context where you reflect what files are actually in a .zip software package rather than merely metadata about the package.

Yes, fully agree. From a licensing audit perspective, the SPDX format is the most complete for detailing what is inside a zip file (product distribution) but an SPDX doc is neither easy to generate nor to maintain by everyday developers. So the ABOUT format surfaced to solve some of these SPDX impairments. What then happens is that the automated tools pick up the ABOUT information generated by developers and merge this data on the generated SPDX.

**Comment by moranegg** [comment]
@andrew  thanks for making it a priority to provide codemeta.json files on libraries.io.

When reading the specs on ABOUT files and the explanations here, seems it is an important part of the metadata landscape and should be crosswalked even if libraries.io will provide the codemeta.json version. The main reason is the possibility to encounter an ABOUT file not only through libraries.io ("text file stored in the codebase side-by-side with the software component file or archive" dejacode/ABOUTspec)

@maxbrito it would be great if you could do the crosswalk as you know .ABOUT so well

> The most relevant aspect of ABOUT is that they apply to specific files and/or folders inside the project, which is needed when different 3rd party s/w get mixed in the same folders and you need to describe exactly which files belong to which component. Maybe a field for specifying files/folders could be included on CodeMeta?

This is an important subject and we should open a separate issue for that (issue #156)

**Comment by maxbrito** [comment]
> do the crosswalk as you know .ABOUT

Happy to provide one.

**Comment by pombredanne** [comment]
Hi there! @maxbrito just pinged me to bring me here. I am behind the .ABOUT file formats originally. I would be happy to help in any way I modestly can.

**Comment by cboettig** [comment]
Thanks @pombredanne @maxbrito , a crosswalk from .ABOUT to codemeta would be great as a Pull Request.  see https://codemeta.github.io/crosswalk/ and ping us if anything isn't clear.  Thanks again!

**Comment by cboettig** [comment]
Closing this as stale, though always open to PR adding crosswalks for `.ABOUT` or any other format
