### ISSUE TITLE
How should the crosswalk table deal with format versions

### ISSUE THREAD

**Issue by sdruskat** [codemeta/codemeta#174]
Thinking about this while I was submitting #173: Should there be an extra header row for crosswalking format version (Does CSV even support this?)? Should all versions be recorded separately in a new crosswalk column? Should format providers decide if and when to update their crosswalk or should CodeMeta provide a policy?

**Comment by cboettig** [comment]
Great question.  Overall the whole CSV approach is not ideal in general here.  (It was a conveniently readable-on-github starting point, but at it's current size the csv version hasn't proven very human-readable either).

A very practical alternative from an applications standpoint would to encode the Crosswalk table would be as a series of `.json` files, one for each column, that literally spell out the mapping for that column; precisely as is done in a  JSON-LD context file; e.g. for the first few [DOAP terms](https://codemeta.github.io/crosswalk/doap/)

```
{
"schema": "http://schema.org/",
"repository": "schema:codeRepository",
"programming-language": "schema:programmingLanguage",
"platform": "runtimePlatform"
}
```

These files can literally be used as context files to automate the translation, e.g. in https://json-ld.org/playground/.  

Having separate files would avoid merge issues, and they could be versioned explicitly (e.g. corresponding to different releases of a given standard, like DataCite) or just versioned directly from the codemeta repo tag or hash.  This also permits more explicit encoding about data types.  

We generate these on the fly from the codemeta csv table in the `codemetar` R package, in order to apply the crosswalks, but maybe maintaining these mappings directly and modularly would be better?  What do you think?

**Comment by moranegg** [comment]
I just stumbled upon a pom.xml file with : <modelVersion>4.0.0</modelVersion> referencing the pom version and not software version. I think this joins @sdruskat query..
As ontologies/schemes tends to evolve as well, we might consider adding the property schemaVersion for coherence. Like with DataCite new schema, some properties were added to the crosswalk, It might be interesting to document this changes. 
 
To answer @cboettig - I think this a very good way to go ! (it should be in a separate issue) 

The duplication of the CodeMeta terms can be subject to more errors or gaps..
If we do this, we should create a small script ensuring the consistency of all files...
And update the table with the added json file, it would be much easier to contribute a json file than adding one column to the table.. (I already have something locally that does that in python, I can clean it up and make it public if you want) 

- [ ] keeping the jsons in a "mappings" folder 
- [ ] generated csv from jsons  at root directory
- [ ] adding information to website about contributing json file and generating updated csv

i do think we should keep the csv anyway.
