### ISSUE TITLE
Identifying CodeMeta files on GitHub

### ISSUE THREAD

**Issue by sdruskat** [codemeta/codemeta#180]
Just a quick question, I've tried searching for CodeMeta files on GitHub recently, and just wanted to confirm that every valid CodeMeta file would a) have to be called `codemeta.json` and b) include the following string (catching schemas v1 and v2):

`https://doi.org/10.5063/schema/codemeta`

In my (limited) experience, properly identifying files via GitHub code search API isn't fool-proof, so I want to make sure that I'm getting the correct files.

Thanks!

**Comment by cboettig** [comment]
@sdruskat Good questions.  

a) Yes 
b) No.

Re b), 

- The DOI URL would still work with either `http` or version or the `dx.doi.org` version as well.  As long as these resolve, they are still valid.  

- Technically the context file does not need to be a link at all, but could literally embed the codemeta context file at the top of a codemeta document.  Obviously this is verbose, but from the JSON-LD point it's semantically equivalent, and has the practical advantage of allowing the JSON-LD algorithms to be applied without a network connection available.  

- Most of the terms in v2 can be expressed in pure schema.org, so it's possible a codemeta.json file will declare the context simply as http://schema.org.  

- Also, as per #125, I've continually had issues with the DataCite content negotiation servers being too slow to successfully use the DOI-based schema, particularly when traffic is high.  To avoid this, there's a fall back url at http://purl.org/codemeta/2.0.   I believe the performance issues we had throughout last year have largely been resolved now though and the DOI-based resolution should work.  

There aren't any technically required fields, but I would expect a `"@type": "SoftwareSourceCode"` field at minimum(?)

**Comment by mbjones** [comment]
Just for clarity, the syntax for the context file namespace is:

   https://doi.org/10.5063/schema/codemeta-2.0

And it seems to be resolving fine and fast now.  So I would recommend that
over the purl at this point.  And definitely version 2,0 and not the early
versions.

Matt

**Comment by sdruskat** [comment]
Thanks!

I've done a quick search for `"@type": "SoftwareSourceCode"` (surrounded by single quotes), which brings up a lot of "plain" schema.org context files ([example](https://github.com/haensl/haensl.github.io.src/blob/4cb24bea7ba2994d9b203c5232258efb056a279f/src/assets/json/minify-inline-json.src.schema.json
)). So either that + any valid URL pointing to the 2.0 schema, or that and a filename check are needed.

**Comment by cboettig** [comment]
@sdruskat I think the filename check would be the most typical.  However, I'd consider all those examples of "plain" schema.org context files to be effectively valid codemeta, in that any properly written application to consume codemeta.json should be able to consume these as well.  

Such files can include fields which are not known to codemeta, but an application should have no problem ignoring these, those fields simply do not compact under codemeta schema.  Codemeta 2.0 defines 10 additional terms not in schema.org, but those aren't required terms.  Otherwise, most terms are identical to codemeta.  

Guess it depends what your use case is, of course.  Presumably the authors in those examples have never heard of codemeta, and are writing schema.org/SoftwareSourceCode descriptions for their own use cases, so this wouldn't measure 'codemeta adoption' per se, but I think it's a win that those files would be 'unknowingly' compatible.

**Comment by cboettig** [comment]
looks to be resolved
