### ISSUE TITLE
How to express End Of Life?

### ISSUE THREAD

**Issue by brucellino** [codemeta/codemeta#192]
Hello codemeta.

Many software products have an end of life calendar. I was wondering what the best way to express this might be. I'm thinking perhaps [`temporalCoverage`](https://schema.org/temporalCoverage) ? But the EOL applies to specific versions.

Any ideas?

**Comment by brucellino** [comment]
I guess this could be expressed via `developmentStatus`...

**Comment by moranegg** [comment]
I would say `developmentStatus` as you suggested if the only information you want to capture is the static current state. If you want to enter a date it will be trickier.

**Comment by cboettig** [comment]
👍 for `developmentStatus`.  

Also a quick tangent re "applies to specific versions":  note that I think it would be typical to interpret all terms in the codemeta file as always describing a particular version already (in particular, note the `version` or `softwareVersion` fields.  More abstractly, these would be attributes of whatever the `@id` of your `softwareSourceCode` object points to, which may or may not be a version stable URI.

**Comment by brucellino** [comment]
I'm ok with `developmentStatus`, but it doesn't express what we need. Many products are fully developed  - _i.e._ feature complete, but still maintained. The closest that repostatus comes to that is `inactive` :+1: 
> The project has reached a stable, usable state but is no longer being actively developed; support/maintenance will be provided as time allows.

What we want to be able to express is both stability, and support status.
If there were a `developmentStatus => supported` which could slot in between `active` and `inactive` I think this may fit the bill. Given that it still wouldn't express a temporal horizon, which we need, it wouldn't be 100% satisfactory. 

So, I am coming to think that the best way to do this is to have a custom field in our schema for this, and adopt the `inactive` or `active` statuses.

**Comment by cboettig** [comment]
@brucellino Ah, right, there's two separate things here.  While I think `developmentStatus` is the appropriate property for this, that doesn't mean you are bound to the repostatus.org vocabulary.  The field takes free text, and you can provide whatever you want.  There's quite a lot of other badge-oriented status vocabularies available as well.  

For instance, the `codemetar` R generator for codemeta also recognizes https://www.tidyverse.org/lifecycle vocabularies, which I like for the very reason you describe: it has more nuance instead of "active" vs "inactive" for more mature software.  There are quite a number of other commonly used vocabularies as well.
