### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by cboettig** [codemeta/codemeta#236]
Are we ready for a new release of the the [codemeta.jsonld](https://github.com/codemeta/codemeta/blob/master/codemeta.jsonld) context file?  Do we do a major or a minor release? (migrated from https://github.com/codemeta/codemeta/pull/235#issuecomment-595388249)

**Comment by mbjones** [comment]
Yeah, I was examining our CodeMeta files in the Google structured data testing tool, and it didn't recognize it as schema.org because wrap the SO terms. So I think we should reconsider that, although I don't seem to be able to replicate it atm.

We also need to ensure that our namespace ends with a `/`, as it currently means our terms append onto the namespace without a separator.

I do like an identifier that resolves to exactly the bytes of our context file, as it makes it self-referential.  That said, if you'd prefer, we can use a namespace that uses a regular https address and redirect from there, which is what we do with our other schemas.  It certainly wasn't easy to get the DOI redirect to work right with the DOI redirection service.

**Comment by moranegg** [comment]
## open issues that might be suited for V3 evolution
- add `review` or `reviewedBy` : https://github.com/codemeta/codemeta/issues/177
- API entry point: https://github.com/codemeta/codemeta/issues/183
- mailing list or `contactPoint` :https://github.com/codemeta/codemeta/issues/166
- link fromSoftwareApplication to SSC with `hasSourceCode`: https://github.com/codemeta/codemeta/issues/198
- input/output formats: https://github.com/codemeta/codemeta/issues/188

**Comment by moranegg** [comment]
When we are ready to move to the CodeMeta v3 or v2.1 we need to add a crosswalk between `v2 -> v3`, like the already existing crosswalk from `v1 -> v2`

**Comment by mbjones** [comment]
@cboettig @moranegg I think at this point many of the changes proposed warrant a v3.0 designation, including the most recent proposal to change the https namespace for schema.org in PR #248. So, I created a new [v3.0 milestone](https://github.com/codemeta/codemeta/milestone/9) for us to use to identify issues and PRs that will be part of the next release. Please review and nominate issues to be included, keeping in mind that issues for which no PR exists might considerably delay release (but still might be warranted). The schema.org task force from Force11 has proposed a number of changes, some of which have been implemented or discussed, and it seems like we should harmonize these and come to agreement on a new release. I will also note that the [Science on Schema.org (SOSO)](https://science-on-schema.org) [release milestone v.1.2](https://github.com/ESIPFed/science-on-schema.org/milestone/5) is coming up, and that covers a number of issues that will apply to CodeMeta as well, particularly their proposal on [provenance relationships between software and data objects](https://github.com/ESIPFed/science-on-schema.org/issues/72) for describing workflows.

So, everyone please nominate issues to include in the release by adding them to the milestone, and let's discuss what the release timing for that might look like. Thanks.

**Comment by moranegg** [comment]
Hi @mbjones I'm very excited about the v3.0.
I will review the open issues and try to propose PRs during this month (October 2020).

Very interesting links on SOSO and the relations between research outputs, thanks.

Concerning the release timing, I believe that a release before the end of 2020 is reasonable.
What did you have in mind?

**Comment by chrishalbert** [comment]
Hi! I know this has gone stale a little, but I wanted to know if [v3](https://github.com/codemeta/codemeta/milestone/9) is simply awaiting pull requests? I have an interest in this particular request: https://github.com/codemeta/codemeta/issues/166, but would be willing to contribute elsewhere to if that's all that is needed.

Thank you for your hardwork!

**Comment by mbjones** [comment]
Hi @chrishalbert -- yes, it's just awaiting community work on the release. There are a lot of outstanding pull requests from the CodeMeta task force and others, which need to be reviewed and merged. I haven't had time to maintain this myself, but my impression was that @moranegg and others from the task force were going to handle that. In looking now, I see that somehow they don't have write access to the repository, so that is likely the problem. Let's discuss admin additions with @moranegg and the CodeMeta task force. Maybe @tmorrell has some thoughts to move forward as well.

**Comment by chrishalbert** [comment]
Thanks for the response @mbjones. I may free up at the end of this week. If so, I can spend some time on code reviews and/or pull requests.

**Comment by tmorrell** [comment]
I'd be happy to help move a release forward. What's the process for moving through the backlog of PRs?

**Comment by mbjones** [comment]
@tmorrell In the past, @cboettig and I have done due diligence to ensure there is community support for a change, and that it doesn't cause compatibility issues, and that the crosswalks and transformations all continue to work with the change via tests. I think some of that review can now happen through community reviews of PRs, and then a final check and merge by a maintainer.  We've taken a fairly conservative stance on breaking changes, but if the group decides breaking changes are needed, I think it should be confined to a single release, and then build incrementally from there. I can make you a maintainer on the repo if @cboettig and others support that. It would be good to define who can serve as maintainer from the CodeMeta task force and elsewhere -- you and @moranegg come to mind as having engaged in the CodeMeta task force a lot, but open to other suggestions.

**Comment by mbjones** [comment]
Also, once all proposed changes are in `develop`, then a final release tag and merge to the main branch would need to be done, along with issuing a new DOI for the new versioned release -- I've been issuing those DOIs from our KNB Data Repository DOI prefix.

One other note -- there is some tooling out there that works with the current release -- e.g., [codemetar](https://github.com/ropensci/codemetar) and [codemeta-generator](https://github.com/codemeta/codemeta-generator). I think we should try to keep those functional, and ensure they continue to work with new releases of the schema.

**Comment by kequach** [comment]
> * Guess we need a changelog summary of the changes since https://doi.org/10.5063/schema/codemeta-2.0.
> 
> To me, this v2.1 or v3.0 might pivot on if we re-define the codemeta context as inclusive of all `schema.org` vocabulary (e.g. codemeta is an extension of schema.org, as it would be if our terms are ever rolled in). I don't think we've ever formally decided on that (#161). Have we made any other edits that would seem like breaking changes?
> 
> Relatedly, our DOI corresponds directly to the codemeta.jsonld file alone, we don't have a 'published' release of the rest of the material in this repo (specifically the crosswalks). (Related to #186). Thoughts on that?

Hello, I wanted to ask about issue #186 (responding here since the issue hasn't been active for a while). I am writing my master thesis on the topic of FAIR research software and am looking to properly cite the CodeMeta project. Considering that you already had this discussion I'd like to push this issue.

**Comment by proycon** [comment]
> One other note -- there is some tooling out there that works with the current release -- e.g., [codemetar](https://github.com/ropensci/codemetar) and [codemeta-generator](https://github.com/codemeta/codemeta-generator). I think we should try to keep those functional, and ensure they continue to work with new releases of the schema.

I agree and think that this a very important point, having good software that complies to the latest codemeta standard can make or break it. I'll do the same for the tools I developed ([codemetapy](https://github.com/proycon/codemetapy), and by extension the new codemeta-harvester and codemeta-server).

**Comment by moranegg** [comment]
We will be closing this task with the V3.0 release.
If you find that some subjects weren't addressed in the upcoming v3.0, please open new tickets.

Cheers and good weekend!

**Comment by stain** [comment]
Will the v3.0 be fully released or is it a release candidate? Several things seem still to be undecided

3.0 is not listed in 
* https://codemeta.github.io/jsonld/ 
* https://github.com/codemeta/codemeta/#codemeta-schema 
* https://github.com/codemeta/codemeta/blob/master/codemeta.json #299

Several issues "tagged for 3.0" were not included:

* `maintainer` switch to schema.org #250 https://github.com/codemeta/codemeta/issues/232#issuecomment-700865287 
* `funding` switch to schema.org #274
* The namespace of https://raw.githubusercontent.com/codemeta/codemeta/3.0/codemeta.jsonld defines terms such as https://codemeta.github.io/terms/readme which is 404  -- these should not use `github.io` and should resolve as PIDs. #216 
* The PID for is not shown on https://codemeta.github.io/terms/ and neither is the version #321

I'm happy to help but at the moment I am quite confused because "3.0" seems to be in a release candidate stage -- perhaps this gives us a change to fix this and call it 3.1?

**Comment by progval** [comment]
> Will the v3.0 be fully released or is it a release candidate? Several things seem still to be undecided
> 
> 3.0 is not listed in
> 
>     * https://codemeta.github.io/jsonld/
> 
>     * https://github.com/codemeta/codemeta/#codemeta-schema
> 
>     * https://github.com/codemeta/codemeta/blob/master/codemeta.json [Update codemeta.json for v3 release #299](https://github.com/codemeta/codemeta/issues/299)

This is still a work in progress

> Several issues "tagged for 3.0" were not included:
> 
>     * `maintainer` switch to schema.org [Switch maintainer to schema.org version #250](https://github.com/codemeta/codemeta/pull/250) [Write proposal for the schema.org adoption of the CodeMeta terms #232 (comment)](https://github.com/codemeta/codemeta/issues/232#issuecomment-700865287)

It's scheduled for 4.0.

>     * `funding` switch to schema.org [Switch funding to schema.org  #274](https://github.com/codemeta/codemeta/pull/274)

Oversight, sorry.

>     * The namespace of https://raw.githubusercontent.com/codemeta/codemeta/3.0/codemeta.jsonld defines terms such as https://codemeta.github.io/terms/readme which is 404  -- these should not use `github.io` and should resolve as PIDs. [Codemeta content negotiation is not correct #216](https://github.com/codemeta/codemeta/issues/216)

The 404 is fine, there is no requirement that IRIs resolve to anything.

Using the `github.io` domain is unfortunate, but that's what we are stuck with.

>     * The PID for is not shown on https://codemeta.github.io/terms/ and neither is the version [Choose identifier for the CodeMeta schema #321](https://github.com/codemeta/codemeta/issues/321)

Could you open a PR to https://github.com/codemeta/codemeta.github.io/ ?

> 3.0 is not yet used by https://codemeta.github.io/codemeta-generator/ -- perhaps waiting for that PID issue.
> 
> I'm happy to help but at the moment I am quite confused because "3.0" seems to be in a beta or release candidate stage -- perhaps as 3.0 is not known outside [GitHub releases](https://github.com/codemeta/codemeta/releases), this gives us a change to fix this and call it 3.1?

We are still working on announcing it and updating the website

**Comment by moranegg** [comment]
Emphasizing @progval that it is still work in progress.

Since the v3.0 is not yet in use (because it's not identifiable yet).
It is in Beta/ release candidate because it can't be used in production.
We have opened the ID discussion on this issue #321 and it seems that we haven't resolved it yet...

I'm inclined to resolve some of the items in @stain 's comment, if possible in a reasonable time.

PRs are always welcome and we are all struggling with time ;-)

My "personal" deadline for this is mid November, because it is needed for the a beta release of other components that are using metadata.

**Comment by moranegg** [comment]
I'm actually going to close this long thread.
If you found missing items in issues or in the next v4.0, please open new issues.
