### ISSUE TITLE
`legalName` in affiliation is invalid?

### ISSUE THREAD

**Issue by vuillaut** [codemeta/codemeta#273]
Dear CodeMeta,

I was unsure how to label this issue, maybe it is just a misunderstanding on my side of how CodeMeta is supposed to work in regard to `schema.org` context.

I realised that some keys that are valid in the `schema.org` context are not in the CodeMeta context. 
As an example, `legalName` is a valid attribute of `affiliation` (under the `Organization` type) in `schema.org`.
However, it is not recognized as valid by the [online generator](https://codemeta.github.io/codemeta-generator/).
Is this the intentional behavior? Or just the validator at fault?

The original issue I raised concerned the cff-converter and can be found here: https://github.com/citation-file-format/cff-converter-python/issues/272

Best regards,

**Comment by dgarijo** [comment]
@vuillaut @tmorrell I think the online generator is meant to be a guide rather than an enforcement.
If something is valid in schema.org, it should be valid in codemeta, as codemeta extends schema.org.

There are other examples where the validator fails, which are technically valid cases. For example, if the repository has a logo, and you use `image` from Schema.org (which is valid for any element), the validator fails. Also, if you have multiple descriptions (e.g., a short description and a long description, or a description of your software in english and another in spanish), the validator will also fail.

**Comment by mbjones** [comment]
I agree that including `legalName` should not create an error. That said, I think the intention of CodeMeta is to provide opinionated guidelines on which schema.org fields really should be provided for software. So, for example, `name` should be used, even if `legalName` is also used, and the absence of `name` should be considered to not be following CodeMeta guidelines. I think the challenge is getting the online generator to work with the essentially unlimited flexibility of the schema.org model -- there are far too many permutations to make a usable user experience in the editor. If you want the full flexibility of the schema.org model, break out your trusty text editor and edit away, rather than trying to do it all in the generator app. So, maybe the editor should stay how it is and edit the documents and fields that it knows how to handle, and a separate validator could be provided that indicates whether any given schema.org entry is valid. The generator might even say something to the effect of "While this document is valid wrt schema.org, it uses fields that the generator is not designed to handle, so will need to be edited elsewhere".

**Comment by moranegg** [comment]
Dear @vuillaut,

Thanks for the comment. 
My suggestion is to open the issue directly in the codemeta-generator repo.
Feedback to improve the generator is very welcome. PRs are welcomed too, when possible.
 
I'm closing this issue here.
Cheers
