### ISSUE TITLE
Add branch to contributing guidelines

### ISSUE THREAD

**Issue by tmorrell** [codemeta/codemeta#347]
What branch should be used for contributions?

In the past the 'develop' branch was used as the target for pull requests, but recently it looks like the 'master' branch has been used. Once we decide, this should be documented in the contributing guidelines.

**Comment by progval** [comment]
Yeah I kind of started using `master` as the branch to land development because there isn't much point in having a branch just to serve released stuff (that's what tags are for).

We might want to keep `develop` for vocabulary changes, so that we can still release non-vocabulary changes (ie. mostly crosswalks) in minor releases without being stuck with stabilization of unrelated changes to the vocabulary

**Comment by bact** [comment]
Will these make sense?

**Vocabulary changes:**

- Add/amend/remove property
- Amend property name
- Amend property type
- Amend property's parent type
- Amend property description, in a way that will change the semantic of the property

**Non-vocabulary changes:**

All other changes that is not included in the vocabulary changes list above, including

- Small amendment to property description, that will NOT change the semantic of the property
- Crosswalk and mapping updates
- Documentation changes (README, etc)

**Comment by bact** [comment]
I have proposed PR #352 for this issue. Can be change upon the discussion here.

**Comment by moranegg** [comment]
Thanks @bact, I have approved the review. will be merged soon.

**Comment by bact** [comment]
Thanks @moranegg, I just spot one typo. Fixed.
