### ISSUE TITLE
Determine appropriate schema / type for all values in codemeta.jsonld

### ISSUE THREAD

**Issue by gothub** [codemeta/codemeta#38]
Several of the terms in codemeta.jsonld have types that are currently serving as 'placeholders' until
more appropriate types can be determined, as neither schema.org or Dublin Core has something
close (maybe we have types added to schema.org or use another schema?). The terms that could be upgraded are:

   -   "accessList": "dcterms:accessRights"
   -  "buildInstructions": "schemaorg:URL"
   -  "citationCount": "schemaorg:integer"
   -  "contIntegration": "schemaorg:URL"
   - "docsCoverage": "schemarg:integer"
   - "downloadCount": "schemarg:integer"
   - "embargoDate": "schemaor:date"
   - "isAomatedBuild": "schemaorg:Text"
   - "package": "schemaorg:Text"
   - "inputs": "schemaorg:Text"
   - "outputs": "schemaorg:Text"
   - "function": "schemaorg:Text"
   - "funding": "schemaorg:Text"
   -  "objectType": "dcterms:type"
   - "programmingLanguage": "schemaorg:Text"
   - "readme": "schemaorg:URL"
   - "issueTracker": "schemaorg:URL"
   - "relatedLink": "schemaorg:URL"
   - "relatedPublications": "schemaorg:URL"
   - "relationship": "schemaorg:Text"
   - "testCoverage": "schemaorg:integer"
   - "zippedCode": "schemaorg:URL"

**Comment by sbpcs59** [comment]
Schema.org can be extended using the mechanism described [here](https://schema.org/docs/extension.html). Proposals for 
"reviewed" (schema.org hosted) extensions are queued as issues in the github [repo](https://github.com/schemaorg/schemaorg/issues). The other option is "externally" hosted extensions
that are hosted outside of schema.org, e.g. the codemeta github repo.

With the changes to [codemeta.jsonld](https://github.com/codemeta/codemeta/blob/master/codemeta.jsonld) from the workshop, the list of
terms that could use more meaningful types is:

-   "isCitable": "schema:Boolean",
-       "isMaintainer": "schema:Boolean",
-       "isRightsHolder": "schema:Boolean",
-       "roleCode": "schema:Text",
-       "citationCount": "schema:integer",
-       "docsCoverage": "schema:integer",
-       "downloadCount": "schema:integer",
-       "embargoDate": "schema:date",
-       "isAutomatedBuild": "schema:Text",
-       "package": "schema:Text",
-       "interactionMethod": "schema:Text",
-       "inputs": "schema:Text",
-       "outputs": "schema:Text",
-       "function": "schema:Text",
-       "funding": "schema:Text",
-       "programmingLanguage": "schema:Text",
-       "readme": "schema:URL",
-       "issueTracker": "schema:URL",
-       "relatedLink": "schema:URL",
-       "relatedPublications": "schema:URL",
-       "relationship": "schema:Text",
-       "testCoverage": "schema:integer",
-       "zippedCode": "schema:URL"

**Comment by mbjones** [comment]
In general, I think we should use the following guidelines in choosing types:

1. If there is an appropriate primitive data type in XSD, use that term
2. If the same concept exactly matches in schema.org, use that term
3. If the same concept exactly matches in Dublin Core, use that term
4. If there is another widespread vocabulary with an exactly matching concept, use that term
5. Otherwise, make up a new term in the CodeMeta namespace
    - We can discuss the appropriate URI for this, but for now use "https://codemeta.github.io/terms/" as the prefix

Here's the list of types to be reviewed one more time, with checkboxes to indicate when a decision was made on each:

- [x] "isCitable": "xsd:boolean",
- [x] "isMaintainer": "xsd:boolean",
- [x] "isRightsHolder": "xsd:boolean",
- [ ] "roleCode": "schema:Text",
- [ ] "citationCount": "xsd:int",
- [ ] "embargoDate": "schema:Date",
- [ ] "isAutomatedBuild": "xsd:boolean",
- [ ] "package": "schema:Text",
- [ ] "funding": "schema:Text",
- [ ] "programmingLanguage": "schema:Text",
- [x] "readme": "schema:URL",
- [x] "issueTracker": "schema:URL",
- [x] "relatedLink": "schema:URL",
- [x] "relatedPublications": "schema:URL",
- [x] "zippedCode": "schema:URL"
- [ ] "license": "schema:license"  (__see issue #67 __)

The following fields are under consideration for modification or removal:
- [ ] "docsCoverage": "xsd:int", (__may be removed__)
- [ ] "downloadCount": "schema:integer", (__may be removed__)
- [ ] "interactionMethod": "schema:Text",
- [ ] "inputs": "schema:Text",
- [ ] "outputs": "schema:Text",
- [ ] "function": "schema:Text",
- [ ] "relationship": "schema:Text",
- [ ] "testCoverage": "schema:integer",

**Comment by gothub** [comment]
The above list of fields to remove / keep has been superseded by the "Keep Concept" column
in `crosswalk.csv`, as that is easier to review, having more information readily available to make
a decision, i.e. definition, how many schemas are using the concept, etc.

@mbjones, @cboettig At our last meeting we didn't get around to reviewing the entries in this column
that are marked with a "?". Should we review this at our next meeting, or just leave comments in the
"Keep Concept" column and reach a consensus that way?

**Comment by cboettig** [comment]
I suspect we could just review and decide on most of them in our next meeting.  Even though we didn't get a chance to formally finalize that we did discuss many of those in Portland already.  I'd suggest we forge ahead for now and then we can ask our workshop team for a last look over our final draft crosswalk, rather than trying to pull people back in to the weeds.  That way at least everyone has a last chance to advocate for any row that we removed, etc.

**Comment by gothub** [comment]
The context is complete as of 6aa13e996fab36c324083c2c3af139ec26c53674, meaning that
all terms and related types have been considered and entered into the context file, which is
now ready for review, so I'm closing this issue which will be superceded by https://github.com/codemeta/codemeta/issues/86
