### ISSUE TITLE
Software Assets

### ISSUE THREAD

**Issue by CaroleGoble** [codemeta/codemeta#42]
**http://ksiresearchorg.ipage.com/seke/seke14paper/seke14paper_71.pdf**

**Comment by mbjones** [comment]
@CaroleGoble Thanks for this pointer.  Are you suggesting that we should crosswalk to this paper?  Reading it over, it seems like a different level of abstraction to me than CodeMeta, albeit related.  For now, we'll think about if and where we should cite this work in the paper, but otherwise I don't see any direct implications for the crosswalk.  Reopen the ticket if you have specific suggestions. Thanks!
