### ISSUE TITLE
for use case table, add 'Additional metadata' column

### ISSUE THREAD

**Issue by mbjones** [codemeta/codemeta#57]
Many of the use case requirements listed in the use case table are necessary but not sufficient to handle the use case.  Adding a column that indicates that 'Additional software metadata' are required for the use case would be useful.

**Comment by cboettig** [comment]
I think use cases and descriptions will be better flushed out in the codemeta paper (and also a page on the codemeta website).  I think this will be better presented in largely narrative form, since this often isn't a binary decision about what field is or isn't useful for what use case.  (Even when it seems obvious -- e.g. dependencies aren't useful for citation use cases, but essential for transitive credit citation use cases)
