### ISSUE TITLE
add mapping to bibtex software entries

### ISSUE THREAD

**Issue by mbjones** [codemeta/codemeta#58]

**Comment by ashleysa** [comment]
I kept thinking about suggesting Zotero. The reason I had not mentioned the need to map it yet, is because I'm assuming there was not a lot of thinking that went into its creation. So, instead of mapping in order to ensure we MEET their requirements, I instead feel like they would be open to adapting to OUR concept of the needed metadata fields once we have a suggestion finalized. 

Do you think I'm naive on the amount of thought that went into the Zotero fields for "computer program"?

**Comment by moranegg** [comment]
Absolutely.
There is the new BibTeX software types that are getting adopted and deserve a mapping:
https://gitlab.inria.fr/gt-sw-citation/bibtex-sw-entry/-/blob/master/swentry.org?ref_type=heads

In the specs there are four types:
- @software 
- @softwaremodule
- @softwareversion
- @codefragment

see- https://www.softwareheritage.org/2020/05/26/citing-software-with-style/

I think that most useful would be a @softwareversion => codemeta mappping.


@hjonin

**Comment by moranegg** [comment]
In the aggregated issue we started a discussion that there should be a mapping for each type (#197)

I'm getting back to this original issue, because it might get noisy in the group issue with comments for other mappings.

**Comment by progval** [comment]
fwiw I have a draft implementation of conversion from Codemeta to BibTex `@software`/`@softwareversion`: https://gitlab.softwareheritage.org/swh/devel/swh-indexer/-/blob/525a54fbcdcce5f0715e8c0ca748af4dde2ffb4d/swh/indexer/bibtex.py . with examples here: https://gitlab.softwareheritage.org/swh/devel/swh-indexer/-/blob/525a54fbcdcce5f0715e8c0ca748af4dde2ffb4d/swh/indexer/tests/test_bibtex.py

**Comment by moranegg** [comment]
Excellent, thanks for the quick feedback.
