### ISSUE TITLE
consider using SPDX for type of license field

### ISSUE THREAD

**Issue by maxogden** [codemeta/codemeta#67]
as used in npm
- http://npm1k.org/
- https://www.npmjs.com/package/spdx

**Comment by mbjones** [comment]
So, this looks really useful, even if not everyone uses it.  So, our definition might suggest that the license field SHOULD use SPDX, but MAY be any character string.  I'm not sure what this implies for the field type in the JSON-LD schema -- need to explore the options.

**Comment by gothub** [comment]
We can use the SPDX `licenseId`, for example "Apache-2.0". The licenses that are known to 
SPDX are enumerated [here](https://spdx.org/licenses/). The CodeMeta concept "License" and
context name "license" can be changed to "LicenseId" and "licenseId". CodeMeta instance files
MAY contain an SPDX known license name, or any other license designation. The CodeMeta
verification tool will check the `licenseId` field and will report if the name is in the SPDX list.

**Comment by mfenner** [comment]
Please provide documentation that SPDX is used for license information. And avoid ambiguity (MAY). Alternatively use license URL.

**Comment by cboettig** [comment]
Schema.org/license uses URL (or creative work), which could be an SPDX URL.  codemeta introduces licenseId, which we state is preferably an SPDX code.  

If we were to enforce this it would be great to have some general utility that was good at mapping the various common abbreviations to their SPDX version.

**Comment by moranegg** [comment]
Is it possible with the current codemeta.jsonld to declare several licenses?

**Comment by cboettig** [comment]
@moranegg I believe any field can take an array, e.g. 

```
"license": [ "https://spdx.org/licenses/GPL-2.-0",  "https://spdx.org/licenses/GPL-3-0"]
```

though it would be merely a convention to assume this should be interpreted as "GPL-2.0 or GPL-3.0"  (a common pattern in R, where many things use the notation `GPL (>= 2.0)`

**Comment by mbjones** [comment]
@cboettig @ashepherd just pointed out that schema.license can be CreativeWork as well as a URL, so that allows full incorporation of the SPDX key and URL for licenses.  See example at https://github.com/earthcubearchitecture-project418/p418Docs/issues/6#issuecomment-358169081

**Comment by cboettig** [comment]
@mbjones Yup, that's a good point.  This doesn't necessarily need any change to the current codemeta context; both schema.org and our context type it as `@id` which can be either node valued or a URI.  

This does get back to the bigger question for CodeMeta as to whether we should just allow any terms from schema.org (#161).  The `@type` fields discussed there (`DigitalDocument`, `PropertyValue`, `propertyID`) are part of schema.org but not currently part of the codemeta context.  That means that if they were included in a codemeta.json file, the JSON-LD operations (e.g. expanding and compacting) would drop these terms as being outside the codemeta context. 

As proposed in #161, I think we'd save ourselves a lot of trouble if we changed the codemeta context to be merely an extension of schema.org, so that any schema.org terms were automatically valid in the codemeta context.  We could still include our extended terms, and we could still maintain some normative documentation on how codemeta should look (e.g. our list of terms, https://codemeta.github.io/terms/, though maybe breaking it down into examples would be better).

**Comment by cboettig** [comment]
@mbjones solution works well here.
