### ISSUE TITLE
Create web app to validate instance files

### ISSUE THREAD

**Issue by gothub** [codemeta/codemeta#89]
This web app will allow the user to cut/paste an instance file into a window (or specify a URL?),
and will then validate the content, listing any errors detected.

How/where can this be deployed? This could be deployed as a github web app as there is a [JavaScript  port](https://github.com/digitalbazaar/jsonld.js) of the JSON-LD API. Should we consider [Heroku](https://www.heroku.com/), or other similar services?

**Comment by gothub** [comment]
Include a check for license type as described in https://github.com/codemeta/codemeta/issues/67.

**Comment by gothub** [comment]
Added an initial version of a client webapp that performs validation of CodeMeta documents. in commit 41bfc663217c9288b9a60f832064c8fa9492de98
Currently this webapp uses the CodeMeta [JSON Schema file](https://github.com/codemeta/codemeta/blob/master/codemeta-json-schema.json), so the document structure and presence of required or incorrect elements is checked. These checks are performed via a JSON Schema validation library [ajv](https://github.com/epoberezkin/ajv), and are limited to the checks available via this library.

This webapp is currently mostly unstyled, so has been made available for comments and ideas.

The following additions could be made:
- [ ] Improve current error messages
- [ ] add styling and CodeMeta attribution
- [ ] add additional checks
- [ ] add a tab for initial document entry
- [ ] add ability to download document from URL
- [ ] when ready for release, install to subdir of https://codemeta.github.io if desired

The webapp is currently available from https://gothub.github.io/ and can be tested by cutting/pasting an example CodeMeta [document](https://raw.githubusercontent.com/codemeta/codemeta/master/examples/example-codemeta-rdataone.json) into the webapp.

**Comment by cboettig** [comment]
:100: nice!

**Comment by BlkPingu** [comment]
I threw the json generated by https://codemeta.github.io/create/ in there and it threw: 
`Error validating the CodeMeta document: data should NOT have additional properties`

Is this supposed to happen?

Code I added:

```json
{
  "@context": "https://doi.org/10.5063/schema/codemeta-2.0",
  "@type": "SoftwareSouceCode",
  "name": "Tobias Kolb",
  "codeRepository": "https://github.com/BlkPingu/attendion",
  "programmingLanguage": "Ruby, C#, FORTRAN",
  "license": "Apache Open Source 2.0",
  "description": "A new way of meeting people",
  "creator": [
    {
      "givenName": "Tobias",
      "familyName": "Kolb",
      "email": "tobias-kolb@hotmail.de",
      "id": "e: https://orcid.org/0000-0002-3843-3472"
    }
  ]
}
```

**Comment by cboettig** [comment]
@BlkPingu Thanks for the bug report.  Unfortunately  https://gothub.github.io/ is a bit out of date, as it is based on version 1.0 schema, which has since been replaced.  

The  https://codemeta.github.io/create/ script is a beta I've just deployed, thanks for testing!  Looks like it has a bug in the type listed above, which I've just fixed.  Not sure how your ORCID line got mangled though, above you have `  "id": "e: https://orcid.org/0000-0002-3843-3472"` (note the extraneous `e:`.  The create tool does automatic validation to ensure this a URI, so it should not have let you do that and I cannot reproduce that bug.  

I've updated https://codemeta.github.io/create/ with a bit more information now.  Note that if you replace the doi-based context with `"http://schema.org", you can also validate in Google's [Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool)
