### ISSUE TITLE
Formalize representation of context term "relationship"

### ISSUE THREAD

**Issue by gothub** [codemeta/codemeta#91]
The context term `relationship` requires additional terms before it can be used to full
potential. The DataCite schema http://schema.datacite.org/meta/kernel-3/doc/DataCite-MetadataKernel_v3.1.pdf has a similiar concept that is represented with three properties:
- relatedIdentifier
- relatedIdentifierType
- relationType

for example:

```
<relatedIdentifier relatedIdentifierType="ISBN"
relationType="IsPartOf">0‐486‐27557‐4
</relatedIdentifier>
```

I propose that we add the terms `relatedIdentifier` and `relationType` using the DataCite controlled list for `relationType` when verifying instance documents. So for example, an instance doc might have:

```
   "relationship":{
       "relationshipType":"isPartOf",
       "relatedIdentifier":"urn:uuid:F1A0A7AF-ECF3-4C7D-B675-7C6949963995"
   }
```

The DataCite list of relation types:
- IsCitedBy
- Cites
- IsSupplementTo
- IsSupplementedBy
- IsContinuedBy
- Continues
- HasMetadata
- IsMetadataFor
- IsNewVersionOf
- IsPreviousVersionOf
- IsPartOf
- HasPart
- IsReferencedBy
- References
- IsDocumentedBy
- Documents
- IsCompiledBy
- Compiles
- IsVariantFormOf
- IsOriginalFormOf
- IsIdenticalTo
- IsReviewedBy
- Reviews
- IsDerivedFrom
- IsSourceOf

**Comment by cboettig** [comment]
:+1: the DataCite model sounds good to me.

**Comment by ljhwang** [comment]
I like this too as it is vary clear.

Does/will your "IdentifierType"s support Githash and DOIs?

Best,
-Lorraine

*****************************
Lorraine Hwang, Ph.D.
Associate Director, CIG
530.752.3656

**Comment by gothub** [comment]
@ljhwang Any value that a CodeMeta instance file author thinks is meaningful they can put
into the `relationshipType` and `relatedIdentifier`, they can. The validation that I mentioned
will just be for informational purposes, but will not accept or reject any value. We want to be
as open as possible, so that any identifier types needed can be used.

This brings up a good point however - will it help consumers of CodeMeta instance files
if the identifier type is specified with a JSON property such as `relatedIdentifierType`? We don't 
currently have this property. My initial thought is to add this, and authors can include
it if desired, as some identifier types include their namespace, i.e. DOIs, LSIDs.

Would this address your concern?

**Comment by ljhwang** [comment]
I think your approach is sound. I think it is good to be explicit and flexible.  

I do note that I had an error in my own personal crosswalk table in that DOI is supported and DataCite had released 4.0 of their metadata scheme!

**Comment by gothub** [comment]
This has been added to the context file and unit tests, but will still need to be
added to the upcoming verification tool and to the documentation. Added in commit
22f9c7dffc084693630bd5e7086a1683d97f3c40

**Comment by gothub** [comment]
Added to the [CodeMeta Developer Guide](https://github.com/codemeta/codemeta/blob/master/developer-guide.md).

**Comment by cboettig** [comment]
@mfenner Just wanted to see if DataCite is still using the above described `relationship` model for its metadata?  Exploring how this lines up with schema.org, it seems at very least one would want to enumerate a Type/class for `Relationship` that had these three properties (`relatedIdentifier`, `relatedIdentifierType`, and `relationType`).

**Comment by mfenner** [comment]
@cboettig DataCite is still using the `relationship` model described at the beginning of this issue. The schema 4.1 that will be released at the end of the year will add `HasVersions/IsVersionOf`  (also in Dublin Core) specifically for the software use case.

After my work in https://github.com/datacite/bolognese mapping DataCite metadata to other schemata I would do things slightly differently if I started fresh, in particular if the metadata model is close to JSON-LD:

* the list of relation types is too long, and in some cases users have problems deciding on what to pick. I would consolidate a bit, e.g. dropping some of the rarely used relation types and use only `references` or `cites`, but not both.
* all DataCite relation types have reverse properties, with the obvious exception of `IsIdenticalTo`. This is very important. I usually need the reverse of the two relation types in schema.org I use most often (`citation` and `isBasedOn`, equivalent to `cites/references` and `isSupplementedBy` in DataCite metadata). Since schema.org doesn't have the reverse relation types I use `@reverse`. There is an ongoing discussion in schemaorg on this, e.g. https://github.com/schemaorg/schemaorg/issues/1156#issuecomment-299252015
* Instead of a generic `relationship` property, use the specific properties at the top level. I am not sure there is value grouping all identifiers together, as you in general you have to go to the specific properties anyway, e.g. for versioning or citation information.
* I would add a `@type`, defaulting to `CreativeWork`. It is very useful to see what thing is related, e.g. is it software - software or software - article. With some related identifiers that is not so obvious.
* instead of `relatedIdentfierType` I would consider always using a URI for `relatedIdentifier`, this simplifies things a bit, and aligns with schema.org - this could be `@id` if in JSON-LD.
* when using this more generic model, it is easy to optionally extend with other properties, `author`, `title`, etc. Crossref does allow that in their `relationship` model, DataCite does not.

A fictive example snippet (valid schema.org):

```
"citation": {
  "@id": "https://github.com/ropensci/geojsonlint",
  "@type: "SoftwareSourceCode",
  "name": "geojsonlint: Tools for Validating 'GeoJSON'
}
```

To me this is nicer than the following:

```
"related_identifier": {
  "relatedIdentifierType": "URL",
  "relationType": "cites",
  "relatedIdentfiier": "https://github.com/ropensci/geojsonlint"
}
```

**Comment by cboettig** [comment]
@mfenner Thanks!  Yup, I agree that the first example is more intuitive for a user to read or write, and being a valid schema.org snippet is also nice.  It's super helpful to lean on your experience here. 

So I'm still trying to grasp how CodeMeta metadata flows to DataCite -- e.g. imagine my goal is that I put my codemeta.json on my GitHub repo, import that to Zenodo or other DataCite-affiliated provider; and ideally I want the DataCite record associated with the DOI they give me to look like the former case (but a very least not simply lose this metadata).  Obviously for the metadata not to be lost the DOI provider has to not ignore it when sending DataCite the metadata, but I have no idea what format connected repos use to send this information to DataCite in the first place.  What does that look like?

Would it be easier / better for, say, Zenodo to have the info in "related_identifer" format in order to get them to pass it along to DataCite?

**Comment by mfenner** [comment]
@cboettig great points, and I am sure part of the discussion of the Force11 Software Citation Implementation Group. The short version of my personal view on this: you should be able to submit metadata in codemeta format when you want to mint a DOI. That is why the library I built for the DataCite DOI content negotiation (https://github.com/datacite/bolognese) converts in both directions: DataCite -> Codemeta, but also Codemeta -> DataCite. This works pretty well already for the metadata that DataCite needs, but the workflow GitHub -> Software Archive -> DataCite needs to be figured out. There are several places where this Codemeta -> DataCite metadata conversion could happen: using a continuous integration tool before sending metadata to software archive, in the software archive, or at DataCite when accepting metadata.

**Comment by cboettig** [comment]
@mfenner Thanks, that's awesome.  So if I understand correctly, this means that the our original  crosswalk for DataCite: http://codemeta.github.io/crosswalk/datacite/ (though I might have missed a few terms) is obsolete, and any metadata in a codemeta.json file, or at least any that uses schema.org terms (?) should successfully crosswalk into the DataCite record (assuming the DOI provider makes the effort instead of just sending whatever it currently sends?)

> There are several places where this Codemeta -> DataCite metadata conversion could happen: using a continuous integration tool before sending metadata to software archive, in the software archive, or at DataCite when accepting metadata.

Interesting. Not clear how these other mechanisms work; from the perspective of a researcher I thought any communication to DataCite was effectively mediated by the DOI-provider though, and I couldn't alter DataCite metadata directly?

**Comment by mfenner** [comment]
Not obsolete, I think there is a difference between mapping metadata, and implementing a tool. The bolognese metadata mapping is at https://github.com/datacite/bolognese/blob/master/lib/bolognese/readers/codemeta_reader.rb, and still needs more work (and codemeta is evolving). There is a separate mapping for schema.org to DataCite. 

This is a Ruby implementation that also works at the command line (and thus works well in continuous integration tools), but I am sure people will do metadata mapping in other languages. I don't know how much effort it would for example be to provide an R wrapper around the command line tool. If you think about that, consider that bolognese also does codemeta -> bibtex and bibtex -> codemeta.

> Interesting. Not clear how these other mechanisms work; from the perspective of a researcher I thought any communication to DataCite was effectively mediated by the DOI-provider though, and I couldn't alter DataCite metadata directly?

That is true. But what you for example could do today is write a little script for your continuous integration tool that takes a codemeta.json file, converts it to DataCite XML and then sends it to the data repository you work with, at least some of them take DataCite XML. I think there is a business opportunity for a data center that archives software and mints DOIs to provide a nice GitHub integration using codemeta.json as input.

**Comment by cboettig** [comment]
@mfenner thanks for the clarification.  Right, tools that translate from set schema (DataCite XML, package Description file, etc) are always going to need manual crosswalking and updating.

I was just wondering if the schema.org serialization of DataCite meant that this could be streamlined for the DataCite case.   e.g. if I understand correctly, you've already mapped from DataCite XML schema <--> schema.org JSON-LD.  If codemeta is using primarily a schema.org context, a tool like `codemeta_reader.rb` could be leveraging that: e.g. just grab all schema.org terms and run them through your schema+jsonld <--> DataCite XML engine to have them in DataCIte XML (which I gather is still your reference format).  

Currently it looks like the `codemeta_reader.rb` ignores the fact that you have mapped between schema and DataCite XML already, and ignores the fact that many codemeta terms are already recognized schema terms, and just manually maps them one by one, right? Perhaps this is/was necessary with codemeta v1 given the differences from schema, but surely that's the more brittle thing we were trying to avoid by using JSON-LD and standardizing to schema.org, right?

**Comment by mfenner** [comment]
Again, I think the mapping is work in progress. I can build a shared library going forward to take advantage of the similarities of codemeta and schema.org. But no need to worry about any of this on your end.

**Comment by cboettig** [comment]
@mfenner Right, I only ask because I think interoperability with DataCite is a priority; and one which has largely driven the original adoption of the `relationship` Type in `codemeta`.  So if sticking with the original structure of relationship means that it's easier for data repositories to get that information into DataCite, we should keep and promote that format within `codemeta`.  

Given that DataCite has defined a nice map to schema.org already though, it seems the best strategy for maximizing what terms can crosswalk into DataCite is simply to maintain alignment with schema.org.

**Comment by cboettig** [comment]
## Summary / Proposal

@mfenner based on your feedback here and the example of the datacite's own JSON-LD, I think there's no longer a compelling case for codemeta to include the `relationship` properties explicitly and we should deprecate them from the codemeta schema.  

If DataCite itself represents these concepts in pure schema.org in it's JSON-LD, it seems rather inconsistent for codemeta metadata to represent them in completely different terms in a `relationship` Type.  In practice I think keeping these terms only fragments codemeta metadata, e.g. any consumer of the data faces the problem that a citation can be encoded in either of the styles you showed above:

```
"citation": {
  "@id": "https://github.com/ropensci/geojsonlint",
  "@type: "SoftwareSourceCode",
  "name": "geojsonlint: Tools for Validating 'GeoJSON'
}
```


```
"related_identifier": {
  "relatedIdentifierType": "URL",
  "relationType": "cites",
  "relatedIdentfiier": "https://github.com/ropensci/geojsonlint"
}
```

We do lose a little expressiveness, but then nothing prevents a user from using additional contexts when necessary, but after all we're trying to normalize rather than fragment here.

**Comment by cboettig** [comment]
closing as we can express this in pure schema.org in the current version
